"""
Seq2Seq (encoder-decoder) extractor for MDS 3.0 fields — Option 1.

Uses a biomedical encoder-decoder model (BioBART, ClinicalT5, SciFive) to extract
MDS 3.0 field values from discharge notes. The bidirectional encoder reads the full
clinical note; the decoder generates structured JSON via cross-attention over the
encoded representation.

Recommended models
------------------
* ``"GanjinZero/biobart-v2-base"``          — BioBART, pre-trained on biomedical text
* ``"luqh/ClinicalT5-large"``               — ClinicalT5, trained on MIMIC notes
* ``"razent/SciFive-large-Pubmed_Pmc"``     — SciFive, biomedical T5

Fine-tuning
-----------
Zero-shot performance is limited because the decoder has never seen the task of
producing MDS JSON. Fine-tune on labeled (discharge note → MDS JSON) pairs using
``scripts/train_seq2seq.py``, then pass the checkpoint path via ``fine_tuned_path``.

What is retained from the preprocessor
---------------------------------------
* ``clean_discharge_text``           — removes MIMIC placeholders and admin noise
* ``format_structured_data_summary`` — includes ICD / Rx context in the prompt

What is dropped
---------------
* Abbreviation expansion  — biomedical models natively understand clinical abbreviations
* Evidence scoring        — the encoder reads the full note bidirectionally
* Knowledge graph format  — structure is learned end-to-end from fine-tuning

Context length constraint
--------------------------
Clinical notes average 2,000–6,000 tokens; most seq2seq models cap at 1,024 (BART)
or 512 (T5). Notes are truncated to ``max_input_length`` tokens. Use a
Longformer-Encoder-Decoder (LED) model for full-length note processing.

Usage
-----
    from src.extractor.seq2seq_extractor import Seq2SeqExtractor
    from src.mapper.seq2seq_mapper import Seq2SeqMapper
    from src.mds_schema import MDSSchema

    schema    = MDSSchema(section_ids=["I", "N", "O"])
    extractor = Seq2SeqExtractor(schema=schema)
    mapper    = Seq2SeqMapper(schema=schema)

    raw        = extractor.extract(note.text, note_metadata=note.metadata)
    assessment = mapper.map(note.note_id, note.subject_id, note.hadm_id, raw)

    # After fine-tuning
    extractor = Seq2SeqExtractor(
        schema=schema,
        fine_tuned_path="output/seq2seq_finetuned",
    )
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional, Sequence

from src.mds_schema import MDSSchema
from src.data_preprocessor.seq2seq_preprocessor import build_seq2seq_input

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Device resolution
# ---------------------------------------------------------------------------
def _resolve_seq2seq_device(prefer_gpu: bool, gpu_device: int) -> str:
    if not prefer_gpu:
        logger.info("Seq2SeqExtractor using CPU (GPU preference disabled).")
        return "cpu"
    try:
        import torch
    except ImportError as exc:
        logger.warning("Seq2SeqExtractor using CPU (torch import failed: %s).", exc)
        return "cpu"
    if not torch.cuda.is_available():
        logger.info("Seq2SeqExtractor using CPU (CUDA not available).")
        return "cpu"
    device_count = torch.cuda.device_count()
    if device_count == 0:
        logger.info("Seq2SeqExtractor using CPU (no CUDA devices detected).")
        return "cpu"
    idx = gpu_device if gpu_device < device_count else 0
    if idx != gpu_device:
        logger.warning(
            "Requested CUDA device %d unavailable (device_count=%d). Falling back to 0.",
            gpu_device,
            device_count,
        )
    name = torch.cuda.get_device_name(idx)
    logger.info("Seq2SeqExtractor using GPU (CUDA device %d: %s).", idx, name)
    return f"cuda:{idx}"


# ---------------------------------------------------------------------------
# Seq2SeqExtractor
# ---------------------------------------------------------------------------
class Seq2SeqExtractor:
    """
    Encoder-decoder extractor for MDS 3.0 fields.

    Parameters
    ----------
    schema:
        MDS schema defining which items to extract.
    model_name:
        Hugging Face model ID of a seq2seq checkpoint (BioBART, ClinicalT5, etc.).
    sections:
        MDS section IDs to extract. Default: ``["I", "N", "O"]``.
    prefer_gpu:
        Use CUDA when available.
    gpu_device:
        CUDA device index.
    max_input_length:
        Maximum encoder token budget. Notes longer than this are truncated
        (tail-first — administrative text at the end is dropped first).
    max_output_length:
        Maximum new tokens generated by the decoder.
    num_beams:
        Beam width for beam-search decoding (higher = more accurate, slower).
    fine_tuned_path:
        Path to a local fine-tuned checkpoint directory. Takes priority over
        ``model_name`` when provided.
    """

    def __init__(
        self,
        schema: Optional[MDSSchema] = None,
        model_name: str = "GanjinZero/biobart-v2-base",
        sections: Optional[Sequence[str]] = None,
        prefer_gpu: bool = True,
        gpu_device: int = 0,
        max_input_length: int = 1024,
        max_output_length: int = 512,
        num_beams: int = 4,
        fine_tuned_path: Optional[str] = None,
    ) -> None:
        self.schema = schema or MDSSchema()
        self.sections = list(sections or ["I", "N", "O"])
        self.max_input_length = max_input_length
        self.max_output_length = max_output_length
        self.num_beams = num_beams
        self.device = _resolve_seq2seq_device(prefer_gpu, gpu_device)
        self._model_name = fine_tuned_path or model_name

        logger.info("Loading Seq2Seq model from '%s'…", self._model_name)
        try:
            from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
            self._tokenizer = AutoTokenizer.from_pretrained(self._model_name)
            self._model = AutoModelForSeq2SeqLM.from_pretrained(self._model_name)
            self._model.to(self.device)
            self._model.eval()
        except Exception as exc:
            raise RuntimeError(
                f"Failed to load seq2seq model '{self._model_name}': {exc}"
            ) from exc
        logger.info("Seq2SeqExtractor ready on device '%s'.", self.device)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def extract(
        self,
        note_text: str,
        note_metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Extract MDS field values from a discharge note.

        Parameters
        ----------
        note_text:
            Raw discharge note text.
        note_metadata:
            Optional metadata dict (may contain ``structured_data``).

        Returns
        -------
        dict
            Flat ``{item_id: value, ..., "confidence": {item_id: float},
            "_raw_output": str, "_model_name": str}`` dict compatible with
            :class:`~mapper.seq2seq_mapper.Seq2SeqMapper`.
        """
        input_text = self._build_input(note_text, note_metadata)
        tokens     = self._tokenize(input_text)
        generated  = self._generate(tokens)
        logger.debug("Seq2SeqExtractor raw output (%.300s).", generated)
        return self._parse_output(generated)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_input(
        self,
        note_text: str,
        note_metadata: Optional[Dict[str, Any]],
    ) -> str:
        section_str = ", ".join(self.sections)

        # Natural-language instruction prefix — T5/BART respond to task prompts
        prefix = (
            f"Extract MDS 3.0 sections {section_str} from the clinical note. "
            "Return a JSON object mapping MDS item IDs to their coded values.\n\n"
        )

        # Simplified preprocessor: clean + structured data + conflict annotations
        # max_chars budget leaves ~100 chars for the prefix before tokenization
        body = build_seq2seq_input(
            note_text=note_text,
            sections=self.sections,
            note_metadata=note_metadata,
            max_chars=3400,
        )

        return prefix + body

    def _tokenize(self, text: str) -> Dict[str, Any]:
        import torch
        tokens = self._tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_input_length,
            padding=False,
        )
        return {k: v.to(self.device) for k, v in tokens.items()}

    def _generate(self, tokens: Dict[str, Any]) -> str:
        import torch
        with torch.no_grad():
            output_ids = self._model.generate(
                **tokens,
                max_new_tokens=self.max_output_length,
                num_beams=self.num_beams,
                early_stopping=True,
            )
        return self._tokenizer.decode(output_ids[0], skip_special_tokens=True)

    def _parse_output(self, generated: str) -> Dict[str, Any]:
        """
        Parse generated text into the flat extraction dict expected by MDSMapper.

        The mapper expects: ``{item_id: value, "confidence": {item_id: float}}``.

        Confidence defaults to 0.8 per item — seq2seq models do not natively
        emit per-item scores. Fine-tuned models can be adapted to output them
        as a second JSON key ``"confidence"``.

        Also attaches ``"_raw_output"`` and ``"_model_name"`` for Seq2SeqMapper.
        """
        raw = self._extract_json(generated)
        if raw is None:
            logger.warning(
                "Seq2SeqExtractor: could not parse JSON from model output "
                "(first 300 chars): %.300s",
                generated,
            )
            return {
                "_raw_output": generated,
                "_model_name": self._model_name,
            }

        # Separate out any nested "confidence" dict the model may have emitted
        confidence: Dict[str, float] = {}
        if isinstance(raw.get("confidence"), dict):
            confidence = raw.pop("confidence")

        # Build flat item_id → value dict; backfill missing confidence scores
        result: Dict[str, Any] = {}
        for item_id, value in raw.items():
            if item_id.startswith("_"):
                continue
            result[item_id] = value
            if item_id not in confidence:
                confidence[item_id] = 0.8

        result["confidence"]   = confidence
        result["_raw_output"]  = generated
        result["_model_name"]  = self._model_name
        return result

    @staticmethod
    def _extract_json(text: str) -> Optional[Dict[str, Any]]:
        """Try to extract a JSON object from generated text."""
        # 1. Entire output is valid JSON
        try:
            obj = json.loads(text.strip())
            if isinstance(obj, dict):
                return obj
        except json.JSONDecodeError:
            pass
        # 2. Find first {...} block in mixed output
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                obj = json.loads(match.group())
                if isinstance(obj, dict):
                    return obj
            except json.JSONDecodeError:
                pass
        return None
